Update instruction data to compatible with Anchor
solana-labs/solana-solidity.js pull request #48
Opened 2022-12-20 12:07 UTC by seanyoung

See https://github.com/hyperledger/solang/pull/1105

2022-12-20 15:43 UTC, LucasSte requested changes
Did you run `yarn fmt` and `yarn lint`?

2022-12-20 15:43 UTC, LucasSte commented on src/contract.ts
> +        const discriminator_image = 'global:' + snakeCase('new');
```suggestion
        const discriminator_image = 'global:new';
```

2022-12-20 15:43 UTC, LucasSte commented on yarn.lock
> +    "readdirp" "~3.6.0"
There is no need to change this file.

2022-12-20 15:43 UTC, LucasSte commented on yarn.lock
> +    "readdirp" "~3.6.0"
You should run `yarn --freeze-lockfile`, if you are not adding a new dependency to the repository.

2022-12-20 15:57 UTC, seanyoung commented
> Did you run `yarn fmt` and `yarn lint`?

Yes, those should be checked in CI now

2022-12-21 11:39 UTC, LucasSte approved these changes

2022-12-21 15:35 UTC, merged